set shell = wscript.createobject("wscript.shell")
shell.run "explorer.exe"
wscript.sleep 100
shell.run "explorer.exe"
wscript.sleep 100
shell.run "explorer.exe"
wscript.sleep 100
shell.run "explorer.exe"
wscript.sleep 100
shell.run "explorer.exe"
wscript.sleep 100
shell.run "explorer.exe"
wscript.sleep 100
shell.run "explorer.exe"
wscript.sleep 100
shell.run "explorer.exe"
wscript.sleep 90
shell.run "explorer.exe"
wscript.sleep 90
shell.run "explorer.exe"
wscript.sleep 90
shell.run "explorer.exe"
wscript.sleep 90
shell.run "explorer.exe"
wscript.sleep 90
shell.run "explorer.exe"
wscript.sleep 90
shell.run "explorer.exe"
wscript.sleep 90
shell.run "explorer.exe"
wscript.sleep 90
shell.run "explorer.exe"
wscript.sleep 90
shell.run "explorer.exe"
wscript.sleep 90
shell.run "explorer.exe"
wscript.sleep 90
shell.run "explorer.exe"
wscript.sleep 40
shell.run "explorer.exe"
wscript.sleep 90
shell.run "explorer.exe"
wscript.sleep 90
shell.run "explorer.exe"
wscript.sleep 90
shell.run "explorer.exe"
wscript.sleep 90
shell.run "explorer.exe"
wscript.sleep 90
shell.run "explorer.exe"
wscript.sleep 90
shell.run "explorer.exe"
wscript.sleep 90
shell.run "explorer.exe"
wscript.quit