set wshshell = createobject("wscript.shell")
do
on error resume next


' PHASE TWO
'-----------
'wshshell.run "mouse.vbs"
wscript.sleep 4000
wshshell.sendkeys " "

wshShell.run "sapi1a.vbs"

wscript.sleep 1000
wshshell.sendkeys " "

wshshell.run "Notepad.exe"

wscript.sleep 1300
wshshell.sendkeys "O"
wscript.sleep 50
wshshell.sendkeys "H"
wscript.sleep 50
wshshell.sendkeys " "

wshShell.run "sapi2a.vbs"

wscript.sleep 50
wshshell.sendkeys "C"
wscript.sleep 50
wshshell.sendkeys "R"
wscript.sleep 50
wshshell.sendkeys "A"
wscript.sleep 50
wshshell.sendkeys "P"
wscript.sleep 50
wshshell.sendkeys ","

wshShell.run "temp.vbs"

wscript.sleep 1000
wshshell.sendkeys " "
wscript.sleep 50
wshshell.sendkeys "M"
wscript.sleep 50
wshshell.sendkeys "Y"
wscript.sleep 50
wshshell.sendkeys " "
wscript.sleep 50
wshshell.sendkeys "B"
wscript.sleep 50
wshshell.sendkeys "O"
wscript.sleep 50
wshshell.sendkeys "Y"
wscript.sleep 50
wshshell.sendkeys " "
wscript.sleep 60
wshshell.sendkeys "Y"
wscript.sleep 60
wshshell.sendkeys "O"
wscript.sleep 60
wshshell.sendkeys "U"
wscript.sleep 40
wshshell.sendkeys " "
wscript.sleep 60
wshshell.sendkeys "J"
wscript.sleep 60
wshshell.sendkeys "U"
wscript.sleep 60
wshshell.sendkeys "S"
wscript.sleep 60
wshshell.sendkeys "T"
wscript.sleep 40
wshshell.sendkeys " "
wscript.sleep 40
wshshell.sendkeys "G"
wscript.sleep 60
wshshell.sendkeys "O"
wscript.sleep 60
wshshell.sendkeys "T"
wscript.sleep 50
wshshell.sendkeys " "
wscript.sleep 50
wshshell.sendkeys "H"
wscript.sleep 50
wshshell.sendkeys "A"
wscript.sleep 50
wshshell.sendkeys "C"
wscript.sleep 50
wshshell.sendkeys "K"
wscript.sleep 50
wshshell.sendkeys "E"
wscript.sleep 50
wshshell.sendkeys "D"
wscript.sleep 10
wshshell.sendkeys "."
wscript.sleep 10
wshshell.sendkeys "."
wscript.sleep 10
wshshell.sendkeys "."
wscript.sleep 10
wshshell.sendkeys "."
wscript.sleep 10
wshshell.sendkeys "."
wscript.sleep 10
wshshell.sendkeys " "
wscript.sleep 50
wshshell.sendkeys "{ENTER}"

wshShell.run "sapi3a.vbs"

wscript.sleep 1500
wshshell.sendkeys "H"
wscript.sleep 50
wshshell.sendkeys "A"
wscript.sleep 50
wshshell.sendkeys "C"
wscript.sleep 50
wshshell.sendkeys "K"
wscript.sleep 50
wshshell.sendkeys "E"
wscript.sleep 50
wshshell.sendkeys "D"
wscript.sleep 50
wshshell.sendkeys " "
wscript.sleep 50
wshshell.sendkeys "I"
wscript.sleep 50
wshshell.sendkeys " "
wscript.sleep 50
wshshell.sendkeys "T"
wscript.sleep 50
wshshell.sendkeys "E"
wscript.sleep 50
wshshell.sendkeys "L"
wscript.sleep 50
wshshell.sendkeys "L"
wscript.sleep 50
wshshell.sendkeys " "
wscript.sleep 50
wshshell.sendkeys "Y"
wscript.sleep 50
wshshell.sendkeys "O"
wscript.sleep 50
wshshell.sendkeys "U"
wscript.sleep 50
wshshell.sendkeys " "
wscript.sleep 50
wshshell.sendkeys "H"
wscript.sleep 50
wshshell.sendkeys "A"
wscript.sleep 50
wshshell.sendkeys "C"
wscript.sleep 50
wshshell.sendkeys "K"
wscript.sleep 50
wshshell.sendkeys "E"
wscript.sleep 50
wshshell.sendkeys "D"
wscript.sleep 50
wshshell.sendkeys " "
wscript.sleep 50
wshshell.sendkeys "L"
wscript.sleep 50
wshshell.sendkeys "O"
wscript.sleep 50
wshshell.sendkeys "L"
wscript.sleep 50
wshshell.sendkeys "!"
wscript.sleep 50
wshshell.sendkeys "!"
wscript.sleep 50
wshshell.sendkeys "!"
wscript.sleep 50
wshshell.sendkeys "!"
wscript.sleep 50
wshshell.sendkeys "!"
wscript.sleep 50
wshshell.sendkeys "!"
wscript.sleep 50
wshshell.sendkeys "!"
wscript.sleep 50
wshshell.sendkeys "!"
wscript.sleep 50
wshshell.sendkeys "1"
wscript.sleep 50
wshshell.sendkeys "1"
wscript.sleep 50
wshshell.sendkeys "1"
wscript.sleep 50
wshshell.sendkeys ","
wscript.sleep 70
wshshell.sendkeys " "
wscript.sleep 50
wshshell.sendkeys "{ENTER}"

wshShell.run "sapi4a.vbs"

wscript.sleep 1500
wshshell.sendkeys "p"
wscript.sleep 50
wshshell.sendkeys "f"
wscript.sleep 50
wshshell.sendkeys "f"
wscript.sleep 50
wshshell.sendkeys "f"
wscript.sleep 50
wshshell.sendkeys "."
wscript.sleep 50
wshshell.sendkeys "."
wscript.sleep 50
wshshell.sendkeys "."
wscript.sleep 50
wshshell.sendkeys " "
wscript.sleep 50
wshshell.sendkeys "W"
wscript.sleep 50
wshshell.sendkeys "h"
wscript.sleep 50
wshshell.sendkeys "o"
wscript.sleep 50
wshshell.sendkeys "'"
wscript.sleep 50
wshshell.sendkeys "s"
wscript.sleep 50
wshshell.sendkeys " "
wscript.sleep 50
wshshell.sendkeys "l"
wscript.sleep 50
wshshell.sendkeys "a"
wscript.sleep 50
wshshell.sendkeys "u"
wscript.sleep 50
wshshell.sendkeys "g"
wscript.sleep 50
wshshell.sendkeys "h"
wscript.sleep 50
wshshell.sendkeys "i"
wscript.sleep 50
wshshell.sendkeys "n"
wscript.sleep 50
wshshell.sendkeys "g"
wscript.sleep 50
wshshell.sendkeys " "
wscript.sleep 50
wshshell.sendkeys "n"
wscript.sleep 50
wshshell.sendkeys "o"
wscript.sleep 50
wshshell.sendkeys "w"
wscript.sleep 20
wshshell.sendkeys "?"
wscript.sleep 20
wshshell.sendkeys "?"
wscript.sleep 20
wshshell.sendkeys "?"
wscript.sleep 20
wshshell.sendkeys "?"
wscript.sleep 20
wshshell.sendkeys "?"

wshShell.run "sapi5a.vbs"

wscript.sleep 20
wshshell.sendkeys "?"
wscript.sleep 20
wshshell.sendkeys "?"
wscript.sleep 20
wshshell.sendkeys "{ENTER}"
wscript.sleep 1000
wshshell.sendkeys "."
wscript.sleep 40
wshshell.sendkeys "M"
wscript.sleep 50
wshshell.sendkeys "U"
wscript.sleep 50
wshshell.sendkeys "A"
wscript.sleep 50
wshshell.sendkeys "H"
wscript.sleep 50
wshshell.sendkeys "A"
wscript.sleep 50
wshshell.sendkeys "H"
wscript.sleep 50
wshshell.sendkeys "A"
wscript.sleep 100
wshshell.sendkeys "U"
wscript.sleep 100
wshshell.sendkeys "A"
wscript.sleep 50
wshshell.sendkeys "G"
wscript.sleep 50
wshshell.sendkeys "H"
wscript.sleep 50
wshshell.sendkeys "J"
wscript.sleep 100
wshshell.sendkeys "AG"
wscript.sleep 200
wshshell.sendkeys "AUG"
wscript.sleep 200
wshshell.sendkeys "HGA"
wscript.sleep 200
wshshell.sendkeys "AGH"
wscript.sleep 100
wshshell.sendkeys "!"
wscript.sleep 50
wshshell.sendkeys "!"
wscript.sleep 25
wshshell.sendkeys "!"
wscript.sleep 80
wshshell.sendkeys "1"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"

wshShell.run "sapi6a.vbs"

wscript.sleep 1500
wshshell.sendkeys "A"
wscript.sleep 50
wshshell.sendkeys "N"
wscript.sleep 50
wshshell.sendkeys "D"
wscript.sleep 50
wshshell.sendkeys " "
wscript.sleep 50
wshshell.sendkeys "G"
wscript.sleep 50
wshshell.sendkeys "U"
wscript.sleep 50
wshshell.sendkeys "E"
wscript.sleep 50
wshshell.sendkeys "S"
wscript.sleep 50
wshshell.sendkeys "S"
wscript.sleep 50
wshshell.sendkeys " "
wscript.sleep 50
wshshell.sendkeys "W"
wscript.sleep 50
wshshell.sendkeys "H"
wscript.sleep 50
wshshell.sendkeys "A"
wscript.sleep 50
wshshell.sendkeys "T"
wscript.sleep 50
wshshell.sendkeys "?"
wscript.sleep 50
wshshell.sendkeys "?"
wscript.sleep 50
wshshell.sendkeys "?"
wscript.sleep 50
wshshell.sendkeys "?"
wscript.sleep 50
wshshell.sendkeys " "

wshShell.run "sapi7a.vbs"

wscript.sleep 1000
wshshell.sendkeys "T"
wscript.sleep 50
wshshell.sendkeys "H"
wscript.sleep 50
wshshell.sendkeys "E"
wscript.sleep 50
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "R"
wscript.sleep 100
wshshell.sendkeys "E"
wscript.sleep 100
wshshell.sendkeys "P"
wscript.sleep 100
wshshell.sendkeys "A"
wscript.sleep 100
wshshell.sendkeys "I"
wscript.sleep 100
wshshell.sendkeys "R"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "W"
wscript.sleep 100
wshshell.sendkeys "I"
wscript.sleep 100
wshshell.sendkeys "L"
wscript.sleep 100
wshshell.sendkeys "L"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "C"
wscript.sleep 100
wshshell.sendkeys "O"
wscript.sleep 100
wshshell.sendkeys "A"
wscript.sleep 100
wshshell.sendkeys "S"
wscript.sleep 100
wshshell.sendkeys "T"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "3"
wscript.sleep 100
wshshell.sendkeys "0"
wscript.sleep 100
wshshell.sendkeys "0"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "D"
wscript.sleep 100
wshshell.sendkeys "O"
wscript.sleep 100
wshshell.sendkeys "L"
wscript.sleep 100
wshshell.sendkeys "L"
wscript.sleep 100
wshshell.sendkeys "A"
wscript.sleep 100
wshshell.sendkeys "R"
wscript.sleep 100
wshshell.sendkeys "S"
wscript.sleep 100
wshshell.sendkeys "!"
wscript.sleep 100
wshshell.sendkeys "."
wscript.sleep 100
wshshell.sendkeys "."
wscript.sleep 100
wshshell.sendkeys "."
wscript.sleep 100
wshshell.sendkeys "{ENTER}"

wshShell.run "sapi8a.vbs"

wscript.sleep 1200
wshshell.sendkeys "n"
wscript.sleep 100
wshshell.sendkeys "o"
wscript.sleep 100
wshshell.sendkeys "w"
wscript.sleep 100
wshshell.sendkeys "."
wscript.sleep 100
wshshell.sendkeys "."
wscript.sleep 100
wshshell.sendkeys "."
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "n"
wscript.sleep 100
wshshell.sendkeys "j"
wscript.sleep 100
wshshell.sendkeys "o"
wscript.sleep 100
wshshell.sendkeys "y"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "t"
wscript.sleep 100
wshshell.sendkeys "h"
wscript.sleep 100
wshshell.sendkeys "i"
wscript.sleep 100
wshshell.sendkeys "s"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "v"
wscript.sleep 100
wshshell.sendkeys "i"
wscript.sleep 100
wshshell.sendkeys "r"
wscript.sleep 100
wshshell.sendkeys "u"
wscript.sleep 100
wshshell.sendkeys "s"
wscript.sleep 100
wshshell.sendkeys "!"
wscript.sleep 100
wshshell.sendkeys ":"
wscript.sleep 80
wshshell.sendkeys "3"
wscript.sleep 800
wshshell.sendkeys "{ENTER}"
wscript.sleep 100
wshshell.sendkeys "L"

wshShell.run "sapi9a.vbs"

wscript.sleep 100
wshshell.sendkeys "O"
wscript.sleep 100
wshshell.sendkeys "V"
wscript.sleep 100
wshshell.sendkeys "E"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "Y"
wscript.sleep 100
wshshell.sendkeys "O"
wscript.sleep 100
wshshell.sendkeys "U"
wscript.sleep 100
wshshell.sendkeys "!"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 800
wshshell.sendkeys "Bye "
wscript.sleep 100
wshshell.sendkeys "Bye"

Sapi.speak "Bye Bye"

wscript.sleep 3000
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 1
wshshell.sendkeys "{BS}"
wscript.sleep 10
wshshell.sendkeys "%{tab}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wscript.sleep 10
wshshell.sendkeys "{F11}"
wshshell.run "MouseMover.vbs"
'-----------
'TRANSITION
wshshell.run "PHASE-3.vbs"

wscript.quit
loop

'Original Creation Date: 3/16/2020 11:03 AM'